- name: Prepare infrastructure
  hosts: all
  tasks:
    - block:
        - include_role:
            name: "{{ role.name }}"
            tasks_from: "{{ role.tasks | default('main.yml') }}"
          when: role.when | default(true)
          loop_control:
            loop_var: role 
          loop:
            - { name: "check" }
            - { name: "s3", when: "{{ backend | bool }}" }
            - { name: "dynamodb", when: "{{ backend | bool }}" }
            - { name: "infrastructure", tasks: "deploy.yml" }
      when: inventory_hostname == groups[group_names[0]][0]
      always:
      - import_role:
          name: s3
          tasks_from: remote-files.yml
        when: backend | bool

