- name: Copy files
  copy:
    src: "roles/infrastructure/files/"
    dest: "/tmp/files-{{ group_names[0] }}/"

- name: Generate remote state configuration file
  template: 
    src: remote-backend-selector.tf.j2 
    dest: "/tmp/files-{{ group_names[0] }}/remote-backend-selector.tf"
  when: backend | bool

- name: Generate remote state variables file
  template:
    src: backend.tfvars.j2
    dest: "/tmp/files-{{ group_names[0] }}/backend.tfvars"
  when: backend | default('false') | bool

- name: Generate regular variables file
  template:
    src: terraform.tfvars.j2
    dest: "/tmp/files-{{ group_names[0] }}/terraform.tfvars"

# Workaround since TF does not support count for modules
# This one should be fixed soon (https://www.hashicorp.com/resources/a-2nd-tour-of-terraform-0-12, section Future plans)
- name: Generate modules file (workaround for Terraform issue 953)
  template:
    src: hosts.tf.j2
    dest: "/tmp/files-{{ group_names[0] }}/hosts.tf"

- name: Generate outputs file (workaround for Terraform issue 953)
  template:
    src: outputs.tf.j2
    dest: "/tmp/files-{{ group_names[0] }}/outputs.tf"
